name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install dependencies
        run: npm install

      - name: Run SonarQube Scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          C:\Users\pc\Desktop\SQ\sonar-scanner-6.2.1.4610-windows-x64\bin\sonar-scanner.bat 
          -D"sonar.projectKey=pr_sonarqube" 
          -D"sonar.sources=." 
          -D"sonar.host.url=http://localhost:9000" 
          -D"sonar.token=sqp_7415c55b3388bf974e7b5de906293c57bd636e35"
